//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskDotNetService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class AirwatchConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static AirwatchConfig defaultInstance = ((AirwatchConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AirwatchConfig())));
        
        public static AirwatchConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string StoreID {
            get {
                return ((string)(this["StoreID"]));
            }
            set {
                this["StoreID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("611000602002773")]
        public string MerchantID {
            get {
                return ((string)(this["MerchantID"]));
            }
            set {
                this["MerchantID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W2773098")]
        public string TerminalID {
            get {
                return ((string)(this["TerminalID"]));
            }
            set {
                this["TerminalID"] = value;
            }
        }
    }
}
