//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KioskDotNetService {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class KioskDotNetConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static KioskDotNetConfig defaultInstance = ((KioskDotNetConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KioskDotNetConfig())));
        
        public static KioskDotNetConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7077")]
        public int LISTEN_PORT {
            get {
                return ((int)(this["LISTEN_PORT"]));
            }
            set {
                this["LISTEN_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public int BUFFER_SIZE {
            get {
                return ((int)(this["BUFFER_SIZE"]));
            }
            set {
                this["BUFFER_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SOCKET_READ_TIMEOUT {
            get {
                return ((int)(this["SOCKET_READ_TIMEOUT"]));
            }
            set {
                this["SOCKET_READ_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LOG_RETAIN_HISTORY {
            get {
                return ((int)(this["LOG_RETAIN_HISTORY"]));
            }
            set {
                this["LOG_RETAIN_HISTORY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KioskDotNetLog")]
        public string LOG_FILE_NAME {
            get {
                return ((string)(this["LOG_FILE_NAME"]));
            }
            set {
                this["LOG_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\KioskDotNet_Log")]
        public string LOG_FILE_PATH {
            get {
                return ((string)(this["LOG_FILE_PATH"]));
            }
            set {
                this["LOG_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KioskDotNetService")]
        public string MODULE_NAME {
            get {
                return ((string)(this["MODULE_NAME"]));
            }
            set {
                this["MODULE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0.1")]
        public string MODULE_VERSION {
            get {
                return ((string)(this["MODULE_VERSION"]));
            }
            set {
                this["MODULE_VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Woolworths Group")]
        public string COMPANY_NAME {
            get {
                return ((string)(this["COMPANY_NAME"]));
            }
            set {
                this["COMPANY_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int LOG_FILE_COUNT {
            get {
                return ((int)(this["LOG_FILE_COUNT"]));
            }
            set {
                this["LOG_FILE_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MAX_LOG_SIZE {
            get {
                return ((int)(this["MAX_LOG_SIZE"]));
            }
            set {
                this["MAX_LOG_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_OPTION_ERROR {
            get {
                return ((bool)(this["LOG_OPTION_ERROR"]));
            }
            set {
                this["LOG_OPTION_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_OPTION_INFO {
            get {
                return ((bool)(this["LOG_OPTION_INFO"]));
            }
            set {
                this["LOG_OPTION_INFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_OPTION_DEBUG {
            get {
                return ((bool)(this["LOG_OPTION_DEBUG"]));
            }
            set {
                this["LOG_OPTION_DEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_OPTION_WARNING {
            get {
                return ((bool)(this["LOG_OPTION_WARNING"]));
            }
            set {
                this["LOG_OPTION_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_OPTION_SQL {
            get {
                return ((bool)(this["LOG_OPTION_SQL"]));
            }
            set {
                this["LOG_OPTION_SQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_OPTION_XML {
            get {
                return ((bool)(this["LOG_OPTION_XML"]));
            }
            set {
                this["LOG_OPTION_XML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_OPTION_KEYS {
            get {
                return ((bool)(this["LOG_OPTION_KEYS"]));
            }
            set {
                this["LOG_OPTION_KEYS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOG_OPTION_SECURE {
            get {
                return ((bool)(this["LOG_OPTION_SECURE"]));
            }
            set {
                this["LOG_OPTION_SECURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string PCEFTPOS_IP {
            get {
                return ((string)(this["PCEFTPOS_IP"]));
            }
            set {
                this["PCEFTPOS_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2999")]
        public int PCEFTPOS_PORT {
            get {
                return ((int)(this["PCEFTPOS_PORT"]));
            }
            set {
                this["PCEFTPOS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string KIOSK_SERVICE_IP {
            get {
                return ((string)(this["KIOSK_SERVICE_IP"]));
            }
            set {
                this["KIOSK_SERVICE_IP"] = value;
            }
        }
    }
}
